"use client"
import Link from "next/link"
import { useLearnerProgress } from "@/store/use-learner-progress"
import { units } from "@/lib/curriculum/units"
import { levelForXp } from "@/lib/curriculum/xp"
import type { Lesson, Unit } from "@/lib/curriculum/types"

export function CourseHero() { const { xp, streak } = useLearnerProgress(); const level = levelForXp(xp); return <section className="rounded-3xl border border-white/10 bg-white/[.04] p-6 shadow-2xl"><p className="text-sm uppercase tracking-[.25em] text-[#00D4FF]">QuantumLoop Academy</p><h1 className="mt-3 text-4xl font-semibold">Curriculum</h1><p className="mt-2 max-w-2xl text-white/60">A structured path from qubits to quantum engineering.</p><div className="mt-6 grid gap-3 sm:grid-cols-4">{[["XP",xp],["Level",level.title],["Streak",`${streak} days`],["Units","9 + capstone"]].map(([k,v])=><div className="rounded-2xl border border-white/10 bg-black/20 p-4" key={String(k)}><p className="text-xs text-white/45">{k}</p><p className="mt-1 text-xl font-semibold text-[#F5B942]">{v}</p></div>)}</div></section> }
export function UnitCard({unit}:{unit:Unit}) { const { lessonsCompleted } = useLearnerProgress(); const done=unit.lessons.filter(l=>lessonsCompleted.includes(l.id)).length; return <Link href={`/curriculum/${unit.id}`} className="group rounded-2xl border border-white/10 bg-white/[.035] p-5 transition hover:-translate-y-1 hover:border-[#00D4FF]/50"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-[#00D4FF]">{unit.level}</p><h2 className="mt-2 text-xl font-semibold">{unit.title}</h2></div><span className="rounded-full border border-[#F5B942]/30 px-2 py-1 text-xs text-[#F5B942]">{done}/{unit.lessons.length}</span></div><p className="mt-3 text-sm text-white/55">{unit.tagline}</p><div className="mt-5 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#00D4FF]" style={{width:`${unit.lessons.length ? done/unit.lessons.length*100 : 0}%`}} /></div><div className="mt-4 flex justify-between text-xs text-white/45"><span>{unit.minutes} min</span><span>{unit.xpTotal} XP</span></div></Link> }
export function LessonList({unit}:{unit:Unit}) { const { lessonsCompleted } = useLearnerProgress(); return <div className="grid gap-3">{unit.lessons.map((lesson:Lesson,i)=><Link key={lesson.id} href={`/curriculum/${unit.id}/${lesson.id}`} className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/[.03] p-4 hover:border-[#00D4FF]/50"><span className="grid size-9 place-items-center rounded-full bg-[#00D4FF]/10 text-sm text-[#00D4FF]">{lessonsCompleted.includes(lesson.id)?"✓":i+1}</span><div className="min-w-0 flex-1"><p className="font-medium">{lesson.title}</p><p className="text-xs text-white/45">{lesson.type} · {lesson.minutes} min</p></div><span className="text-sm text-[#F5B942]">+{lesson.xp} XP</span></Link>)}</div> }
