import type { Unit } from "./types"

const lesson = (unit: string, id: string, title: string, type: "Concept" | "Interactive" | "Studio task" | "Lab", text: string, link = "/curriculum") => ({ id: `${unit}-${id}`, title, type, minutes: 12, xp: type === "Concept" ? 10 : 15, sections: [{ type: "heading" as const, text: title }, { type: "paragraph" as const, text }, { type: "callout" as const, tone: "key" as const, text: "Pending faculty review: use this checkpoint to connect the idea to a real circuit." }], checkpoints: [{ id: `${unit}-${id}-q1`, prompt: "Which statement is most accurate?", options: ["Amplitudes determine probabilities after squaring", "A qubit is always both classical values", "Measurement reveals every amplitude", "Phase is the same as probability"], answer: 0, explanation: "Quantum amplitudes are complex numbers; measurement probabilities are their squared magnitudes." }, { id: `${unit}-${id}-q2`, prompt: "What should you do next?", options: ["Test the idea with a small example", "Skip every measurement", "Treat an analogy as a proof", "Ignore normalization"], answer: 0, explanation: "Small examples make abstract quantum behavior testable." }, { id: `${unit}-${id}-q3`, prompt: "Is this lesson ready to review?", options: ["Yes", "Only after answering", "Never", "Only with hardware"], answer: 1, explanation: "Answering checkpoints unlocks the next section." }], takeaways: ["Separate amplitudes from probabilities.", "Use measurement results to test predictions."], links: [{ label: "Open related tool", href: link }] })

const specs: Array<[string,string,string,string, string, string]> = [
["u1","Quantum Foundations","How qubits extend classical information","Beginner","Quantum computing uses quantum states to process information. A classical bit is either 0 or 1; a qubit is described by amplitudes α and β with |α|² + |β|² = 1. Measurement samples an outcome and changes the state. Superposition is not uncertainty caused by missing knowledge: it is a state with multiple amplitudes. Relative phase affects interference, while global phase does not change measurement probabilities.","/lab"],
["u1","Qubits and measurement","From amplitudes to probability","Beginner","For |ψ⟩ = α|0⟩ + β|1⟩, measuring in the computational basis returns 0 with probability |α|² and 1 with probability |β|². Repeating the experiment estimates these probabilities; one shot does not reveal the whole state. The Bloch sphere is a geometric representation of a pure single-qubit state, with poles for |0⟩ and |1⟩ and phase represented around the equator.","/lab"],
["u1","Phase and interference","Why phase matters","Beginner","Two states can have the same measurement probabilities but different relative phase. A later gate can make their amplitudes add or cancel. This is the engine of many algorithms: computation arranges interference so useful answers become more likely. A global phase e^{iγ}|ψ⟩ is physically unobservable, but a relative phase between basis states is observable through interference.","/lab"],
["u2","Gate toolkit","X, H, Z, rotations","Beginner","Quantum gates are reversible unitary transformations. X swaps |0⟩ and |1⟩; H maps |0⟩ to (|0⟩+|1⟩)/√2; Z changes the phase of |1⟩. Y and rotations add other axes of control. Unitary means U†U=I, so the operation preserves total probability and has an inverse.","/studio"],
["u2","Reading circuits","Time flows left to right","Beginner","A circuit diagram is a timeline for qubits. Wires are qubit registers and gates act at a moment in time. A controlled gate applies an operation only when a control condition is met. Read barriers carefully: gates on different qubits may be parallel, but measurement is not an ordinary reversible gate.","/studio"],
["u2","Multi-qubit gates","CNOT, CZ and SWAP","Beginner","Multi-qubit systems use tensor products. CNOT flips the target when the control is 1; applied after H, it can create a Bell state. CZ changes a phase when both qubits are 1. SWAP exchanges states. These gates let circuits create correlations that cannot be represented as independent single-qubit states.","/studio"],
]
const baseUnits: Array<{id:string;title:string;tagline:string;level:"Beginner"|"Intermediate"|"Advanced";badge:string;tools:string[]; prereq:string[]}> = [
{id:"u1",title:"Quantum Foundations",tagline:"Build the mental model for qubits, measurement, and phase.",level:"Beginner",badge:"Foundations Cadet",tools:["Lab"],prereq:[]},{id:"u2",title:"Gates and Circuits",tagline:"Read, build, and reason about quantum circuits.",level:"Beginner",badge:"Gate Wrangler",tools:["Circuit Studio"],prereq:["u1"]},{id:"u3",title:"Entanglement",tagline:"Understand tensor products, Bell states, and teleportation.",level:"Intermediate",badge:"Entanglement Explorer",tools:["Lab"],prereq:["u2"]},{id:"u4",title:"First Algorithms",tagline:"See how oracles and interference create speedups.",level:"Intermediate",badge:"Oracle Whisperer",tools:["Lab"],prereq:["u3"]},{id:"u5",title:"Search and Fourier Methods",tagline:"Explore Grover, QFT, phase estimation, and Shor.",level:"Advanced",badge:"Amplitude Amplifier",tools:["Lab"],prereq:["u4"]},{id:"u6",title:"Variational Algorithms",tagline:"Connect parameterized circuits to optimization.",level:"Advanced",badge:"Variational Voyager",tools:["Circuit Studio"],prereq:["u5"]},{id:"u7",title:"Noise and Error Correction",tagline:"Model errors and the road to fault tolerance.",level:"Advanced",badge:"Noise Navigator",tools:["Lab"],prereq:["u6"]},{id:"u8",title:"Circuit Studio Mastery",tagline:"Turn concepts into reproducible experiments.",level:"Intermediate",badge:"Studio Craftsman",tools:["Circuit Studio"],prereq:["u2"]},{id:"u9",title:"Hardware Studio Mastery",tagline:"Design the cryogenic system around a quantum processor.",level:"Advanced",badge:"Cryostat Architect",tools:["Hardware Studio"],prereq:["u7"]}]
export const units: Unit[] = baseUnits.map((u) => { const selected = specs.filter((s) => s[0] === u.id); const lessons = selected.length ? selected.map((s) => lesson(s[0], s[1].toLowerCase().replaceAll(" ","-"), s[1], s[3] as never, s[4], s[5])) : [lesson(u.id,"core",u.title,"Concept",u.tagline)]; return {...u, prerequisites:u.prereq, lessons, minutes: lessons.reduce((n,l)=>n+l.minutes,0), xpTotal: lessons.reduce((n,l)=>n+l.xp,0)} })
export const getUnit = (id: string) => units.find((unit) => unit.id === id)
export const getLesson = (unitId: string, lessonId: string) => getUnit(unitId)?.lessons.find((l) => l.id === lessonId)
