import type { CircuitGate, SimulationResult } from "@/lib/algorithms/types"

type Complex = { re: number; im: number }
const add = (a: Complex, b: Complex): Complex => ({ re: a.re + b.re, im: a.im + b.im })
const mul = (a: Complex, b: Complex): Complex => ({ re: a.re * b.re - a.im * b.im, im: a.re * b.im + a.im * b.re })
const phase = (theta: number): Complex => ({ re: Math.cos(theta), im: Math.sin(theta) })
function applySingle(state: Complex[], qubits: number, q: number, matrix: Complex[][]) { const bit = 1 << q; for (let i = 0; i < state.length; i++) if ((i & bit) === 0) { const j = i | bit; const a = state[i], b = state[j]; state[i] = add(mul(matrix[0][0], a), mul(matrix[0][1], b)); state[j] = add(mul(matrix[1][0], a), mul(matrix[1][1], b)) } }
function applyControlled(state: Complex[], control: number, target: number, theta: number) { const c = 1 << control, t = 1 << target; for (let i = 0; i < state.length; i++) if ((i & c) && (i & t)) state[i] = mul(state[i], phase(theta)) }
export async function runCircuit(qubits: number, gates: CircuitGate[], shots = 1024, noisePercent = 0): Promise<SimulationResult> { const state = Array.from({ length: 1 << qubits }, (_, i) => ({ re: i === 0 ? 1 : 0, im: 0 })); const h = 1 / Math.sqrt(2); for (const gate of gates) { const q = gate.qubit; if (gate.gate === "H") applySingle(state, qubits, q, [[{ re: h, im: 0 }, { re: h, im: 0 }], [{ re: h, im: 0 }, { re: -h, im: 0 }]]); else if (["X", "Y", "Z"].includes(gate.gate)) { const matrices: Record<string, Complex[][]> = { X: [[{ re: 0, im: 0 }, { re: 1, im: 0 }], [{ re: 1, im: 0 }, { re: 0, im: 0 }]], Y: [[{ re: 0, im: 0 }, { re: 0, im: -1 }], [{ re: 0, im: 1 }, { re: 0, im: 0 }]], Z: [[{ re: 1, im: 0 }, { re: 0, im: 0 }], [{ re: 0, im: 0 }, { re: -1, im: 0 }]] }; applySingle(state, qubits, q, matrices[gate.gate]) } else if (gate.gate === "S" || gate.gate === "T") applySingle(state, qubits, q, [[{ re: 1, im: 0 }, { re: 0, im: 0 }], [{ re: 0, im: 0 }, phase(gate.gate === "S" ? Math.PI / 2 : Math.PI / 4)]]); else if (gate.gate === "CP") applyControlled(state, gate.control ?? q, gate.target ?? (q === 0 ? 1 : 0), gate.theta ?? Math.PI / 2) }
 const probabilities = Object.fromEntries(state.map((a, i) => [i.toString(2).padStart(qubits, "0"), a.re * a.re + a.im * a.im])); const counts: Record<string, number> = {}; for (let shot = 0; shot < shots; shot++) { let r = Math.random(), key = Object.keys(probabilities)[0]; for (const [k, p] of Object.entries(probabilities)) { r -= p; if (r <= 0) { key = k; break } } counts[key] = (counts[key] ?? 0) + 1 } return { counts, probabilities, statevector: state, blochVectors: Array.from({ length: qubits }, () => ({ x: 0, y: 0, z: 1 })) } }
