import type { HardwareComponent } from "./types"

const REF = "Reference values, verify with vendor datasheets."

export const COMPONENTS: HardwareComponent[] = [
  {
    id: "attenuator",
    name: "Attenuator",
    abbreviation: "Atten",
    category: "Passive",
    description:
      "A fixed-value RF attenuator that dumps signal power into a resistive network, reducing thermal and amplifier noise before it reaches the qubit. Stacked in a few stages so each plate only has to absorb a modest amount of heat.",
    dimensionsMm: { x: 8.4, y: 25.5, z: 8.4 },
    compatibleStages: [
      { stageId: "50K", preferred: true },
      { stageId: "4K", preferred: true },
      { stageId: "Still", preferred: true },
      { stageId: "CP", preferred: true },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["xy", "readout-in"],
    ports: [
      { id: "in", name: "RF In", direction: "in", connector: "SMA" },
      { id: "out", name: "RF Out", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Value", value: "10–30 dB" },
      { label: "Bandwidth", value: "DC – 18 GHz" },
      { label: "Impedance", value: "50 Ω" },
    ],
    powerDissipationW: 0.0005,
    massG: 12,
    model: { shape: "attenuator", finish: "gold-copper" },
    referenceNote: REF,
  },
  {
    id: "lowpass-filter",
    name: "Low-pass Filter",
    abbreviation: "LPF",
    category: "Passive",
    description:
      "A coaxial low-pass block that removes high-frequency noise and thermal photons above its cutoff while passing the drive/flux tone cleanly. Machined block construction keeps insertion loss low in the passband.",
    dimensionsMm: { x: 29, y: 11, z: 20 },
    compatibleStages: [
      { stageId: "4K", preferred: true },
      { stageId: "Still", preferred: true },
      { stageId: "CP", preferred: true },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["flux", "dc-bias"],
    ports: [
      { id: "in", name: "In", direction: "in", connector: "SMA" },
      { id: "out", name: "Out", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Cutoff", value: "1–12 GHz" },
      { label: "Insertion loss", value: "< 1 dB" },
      { label: "Rejection", value: "> 40 dB stopband" },
    ],
    powerDissipationW: 0,
    massG: 22,
    model: { shape: "lowpass-filter", finish: "blue-anodized" },
    referenceNote: REF,
  },
  {
    id: "circulator",
    name: "Circulator",
    abbreviation: "Circ",
    category: "Passive",
    description:
      "A 3-port non-reciprocal device that routes signal power 1→2→3→1 only. Isolates the qubit's readout resonator from noise reflected back down the amplification chain.",
    dimensionsMm: { x: 82, y: 24.64, z: 22.4 },
    compatibleStages: [
      { stageId: "4K", preferred: false },
      { stageId: "CP", preferred: false },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["readout-out"],
    ports: [
      { id: "p1", name: "Port 1 (from sample)", direction: "in", connector: "SMA" },
      { id: "p2", name: "Port 2 (to HEMT)", direction: "out", connector: "SMA" },
      { id: "p3", name: "Port 3 (50 ohm load)", direction: "bidirectional", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Band", value: "4–8 GHz" },
      { label: "Isolation", value: "~60 dB" },
      { label: "Insertion loss", value: "~0.4 dB" },
    ],
    powerDissipationW: 0,
    massG: 45,
    model: { shape: "circulator", finish: "blue-anodized" },
    referenceNote: REF,
  },
  {
    id: "hemt",
    name: "HEMT Amplifier",
    abbreviation: "HEMT",
    category: "Active",
    description:
      "A low-noise cryogenic amplifier that provides the first big gain stage on the way back out of the fridge. Its noise temperature dominates the whole readout chain's sensitivity, so it lives right at 4K where cooling power is still generous.",
    dimensionsMm: { x: 39.2, y: 20, z: 7.8 },
    compatibleStages: [{ stageId: "4K", preferred: true }],
    compatibleLines: ["readout-out"],
    ports: [
      { id: "rfin", name: "RF In", direction: "in", connector: "SMA" },
      { id: "rfout", name: "RF Out", direction: "out", connector: "SMA" },
      { id: "dc", name: "DC Bias", direction: "in", connector: "Nano-D" },
    ],
    keySpecs: [
      { label: "Gain", value: "35–42 dB" },
      { label: "Noise temp.", value: "2–5 K" },
      { label: "Band", value: "4–8 GHz" },
    ],
    powerDissipationW: 0.015,
    massG: 18,
    model: { shape: "hemt", finish: "gold-copper" },
    referenceNote: REF,
  },
  {
    id: "thermometer",
    name: "Thermometer",
    abbreviation: "Therm",
    category: "Sensor",
    description:
      "A Cernox or RuOx resistance sensor read out with a 4-wire DC measurement, used to monitor the actual temperature of each stage during cooldown and operation.",
    dimensionsMm: { x: 8, y: 4, z: 6 },
    compatibleStages: [
      { stageId: "50K", preferred: false },
      { stageId: "4K", preferred: true },
      { stageId: "Still", preferred: false },
      { stageId: "CP", preferred: false },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["dc-bias"],
    ports: [
      { id: "sp", name: "Sense+", direction: "bidirectional", connector: "Nano-D" },
      { id: "sn", name: "Sense-", direction: "bidirectional", connector: "Nano-D" },
    ],
    keySpecs: [
      { label: "Range", value: "10 mK – 100 K" },
      { label: "Readout", value: "4-wire DC" },
      { label: "Sensor", value: "Cernox / RuOx" },
    ],
    powerDissipationW: 0.000001,
    massG: 0.5,
    model: { shape: "thermometer", finish: "ceramic" },
    referenceNote: REF,
  },
  {
    id: "connector",
    name: "Connector",
    abbreviation: "Conn",
    category: "Interface",
    description:
      "An SMA bulkhead jack that passes a signal through a panel or plate. The workhorse interface between cable runs and the feedthrough panels at each stage.",
    dimensionsMm: { x: 12.7, y: 22.23, z: 12.7 },
    compatibleStages: [
      { stageId: "300K", preferred: true },
      { stageId: "50K", preferred: false },
      { stageId: "4K", preferred: false },
      { stageId: "Still", preferred: false },
      { stageId: "CP", preferred: false },
      { stageId: "MXC", preferred: false },
    ],
    compatibleLines: ["xy", "flux", "readout-in", "readout-out", "dc-bias"],
    ports: [{ id: "port", name: "Port", direction: "bidirectional", connector: "SMA" }],
    keySpecs: [
      { label: "Type", value: "SMA bulkhead jack" },
      { label: "Band", value: "DC – 18 GHz" },
      { label: "Above 18 GHz", value: "Use K-connector" },
    ],
    powerDissipationW: 0,
    massG: 8,
    model: { shape: "connector", finish: "brass" },
    referenceNote: REF,
  },
  {
    id: "bias-tee",
    name: "Bias Tee",
    abbreviation: "Bias-T",
    category: "Passive",
    description:
      "Combines a DC bias current with an RF signal onto a single line, letting a flux or drive line carry both a fast AC tone and a slow DC offset on the same cable.",
    dimensionsMm: { x: 30, y: 12, z: 12 },
    compatibleStages: [
      { stageId: "4K", preferred: false },
      { stageId: "Still", preferred: false },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["flux", "xy"],
    ports: [
      { id: "rf", name: "RF", direction: "in", connector: "SMA" },
      { id: "dc", name: "DC", direction: "in", connector: "Nano-D" },
      { id: "out", name: "RF+DC Out", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Band", value: "DC – 12 GHz" },
      { label: "DC path", value: "Up to 200 mA" },
      { label: "Insertion loss", value: "< 0.3 dB" },
    ],
    powerDissipationW: 0,
    massG: 15,
    model: { shape: "bias-tee", finish: "gold-copper" },
    referenceNote: REF,
  },
  {
    id: "isolator",
    name: "Isolator",
    abbreviation: "Iso",
    category: "Passive",
    description:
      "A single-direction RF device — essentially a circulator with the third port permanently terminated — used for a compact extra stage of reverse isolation on the readout-out chain.",
    dimensionsMm: { x: 60, y: 20, z: 18 },
    compatibleStages: [
      { stageId: "CP", preferred: false },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["readout-out"],
    ports: [
      { id: "in", name: "In", direction: "in", connector: "SMA" },
      { id: "out", name: "Out", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Isolation", value: "~20 dB" },
      { label: "Band", value: "4–8 GHz" },
      { label: "Insertion loss", value: "~0.5 dB" },
    ],
    powerDissipationW: 0,
    massG: 30,
    model: { shape: "isolator", finish: "blue-anodized" },
    referenceNote: REF,
  },
  {
    id: "directional-coupler",
    name: "Directional Coupler",
    abbreviation: "Coup",
    category: "Passive",
    description:
      "Taps off a small, well-defined fraction of a signal (commonly ~20 dB down) onto a monitor port, useful for test signals, calibration tones or diagnostics without disturbing the main line.",
    dimensionsMm: { x: 45, y: 16, z: 16 },
    compatibleStages: [
      { stageId: "4K", preferred: false },
      { stageId: "Still", preferred: false },
      { stageId: "MXC", preferred: false },
    ],
    compatibleLines: ["readout-in", "readout-out"],
    ports: [
      { id: "in", name: "In", direction: "in", connector: "SMA" },
      { id: "out", name: "Out", direction: "out", connector: "SMA" },
      { id: "coupled", name: "Coupled (monitor)", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Coupling", value: "~20 dB" },
      { label: "Band", value: "2–8 GHz" },
      { label: "Directivity", value: "> 20 dB" },
    ],
    powerDissipationW: 0,
    massG: 25,
    model: { shape: "directional-coupler", finish: "blue-anodized" },
    referenceNote: REF,
  },
  {
    id: "ir-filter",
    name: "Infrared / Eccosorb Filter",
    abbreviation: "IR",
    category: "Passive",
    description:
      "An absorptive filter packed with a lossy composite (Eccosorb-style) that blocks stray infrared photons and quasiparticle-generating radiation from reaching the qubit, without the sharp cutoff ringing of a reactive filter.",
    dimensionsMm: { x: 20, y: 20, z: 30 },
    compatibleStages: [
      { stageId: "Still", preferred: true },
      { stageId: "CP", preferred: true },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["xy", "flux", "readout-in"],
    ports: [
      { id: "in", name: "In", direction: "in", connector: "SMA" },
      { id: "out", name: "Out", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Absorber", value: "Eccosorb-style composite" },
      { label: "Band", value: "Broadband IR rejection" },
      { label: "Insertion loss", value: "~1–2 dB in-band" },
    ],
    powerDissipationW: 0,
    massG: 20,
    model: { shape: "ir-filter", finish: "gold-copper" },
    referenceNote: REF,
  },
  {
    id: "parametric-amp",
    name: "Parametric Amplifier",
    abbreviation: "JPA",
    category: "Active",
    description:
      "A Josephson or traveling-wave parametric amplifier (JPA/TWPA) that provides near quantum-limited gain as the very first amplification stage, right at the coldest plate, before the signal-to-noise ratio is degraded by anything warmer.",
    dimensionsMm: { x: 25, y: 15, z: 5 },
    compatibleStages: [
      { stageId: "CP", preferred: false },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["readout-out"],
    ports: [
      { id: "sigin", name: "Signal In", direction: "in", connector: "SMA" },
      { id: "sigout", name: "Signal Out", direction: "out", connector: "SMA" },
      { id: "pump", name: "Pump", direction: "in", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Gain", value: "~20 dB" },
      { label: "Added noise", value: "Near quantum limit" },
      { label: "Bandwidth", value: "Hundreds of MHz – several GHz (TWPA)" },
    ],
    powerDissipationW: 0.0000001,
    massG: 5,
    model: { shape: "parametric-amp", finish: "black-anodized" },
    referenceNote: REF,
  },
  {
    id: "feedthrough-panel",
    name: "Feedthrough Panel",
    abbreviation: "Panel",
    category: "Interface",
    description:
      "A hermetic feedthrough plate mounted at the 300K flange, carrying a grid of RF and DC connectors that bring every signal line from room-temperature electronics into the vacuum can.",
    dimensionsMm: { x: 200, y: 10, z: 200 },
    compatibleStages: [{ stageId: "300K", preferred: true }],
    compatibleLines: ["xy", "flux", "readout-in", "readout-out", "dc-bias"],
    ports: [
      { id: "grid", name: "Feedthrough grid", direction: "bidirectional", connector: "SMA" },
      { id: "dcgrid", name: "DC grid", direction: "bidirectional", connector: "Nano-D" },
    ],
    keySpecs: [
      { label: "Ports", value: "Configurable grid" },
      { label: "Seal", value: "Hermetic, vacuum rated" },
      { label: "Mixed", value: "RF + DC in one panel" },
    ],
    powerDissipationW: 0,
    massG: 450,
    model: { shape: "feedthrough-panel", finish: "steel" },
    referenceNote: REF,
  },
  {
    id: "dc-filter",
    name: "Cryo Low-Noise DC Filter",
    abbreviation: "RC",
    category: "Passive",
    description:
      "An RC or copper-powder filter that removes high-frequency noise from DC bias and flux lines before they reach the sample, without disturbing the (near-DC) signal itself.",
    dimensionsMm: { x: 15, y: 10, z: 10 },
    compatibleStages: [
      { stageId: "CP", preferred: false },
      { stageId: "MXC", preferred: true },
    ],
    compatibleLines: ["dc-bias"],
    ports: [
      { id: "in", name: "In", direction: "in", connector: "Nano-D" },
      { id: "out", name: "Out", direction: "out", connector: "Nano-D" },
    ],
    keySpecs: [
      { label: "Type", value: "RC / copper-powder" },
      { label: "Cutoff", value: "~1 kHz – 1 MHz class" },
      { label: "DC resistance", value: "Low, but nonzero" },
    ],
    powerDissipationW: 0,
    massG: 4,
    model: { shape: "dc-filter", finish: "black-anodized" },
    referenceNote: REF,
  },
  {
    id: "sample-holder",
    name: "Qubit Sample Holder",
    abbreviation: "QPU",
    category: "Device",
    description:
      "A gold-plated copper box that houses the transmon chip (the QPU package) at the mixing chamber — the coldest, most shielded point in the whole fridge. Everything else in the wiring diagram exists to serve this one part.",
    dimensionsMm: { x: 40, y: 40, z: 10 },
    compatibleStages: [{ stageId: "MXC", preferred: true }],
    compatibleLines: ["xy", "flux", "readout-in", "readout-out"],
    ports: [
      { id: "xy", name: "XY", direction: "in", connector: "SMA" },
      { id: "flux", name: "Flux", direction: "in", connector: "SMA" },
      { id: "roin", name: "Readout In", direction: "in", connector: "SMA" },
      { id: "roout", name: "Readout Out", direction: "out", connector: "SMA" },
    ],
    keySpecs: [
      { label: "Chip", value: "Transmon (superconducting)" },
      { label: "Shielding", value: "Cu box + magnetic shield" },
      { label: "Thermalization", value: "Direct MXC plate mount" },
    ],
    powerDissipationW: 0,
    massG: 60,
    model: { shape: "sample-holder", finish: "gold-copper" },
    referenceNote: REF,
  },
]

export const COMPONENT_MAP: Record<string, HardwareComponent> = Object.fromEntries(COMPONENTS.map((c) => [c.id, c]))

export function getComponent(id: string): HardwareComponent | undefined {
  return COMPONENT_MAP[id]
}
