"use client"

import Link from "next/link"
import { useState } from "react"
import { ArrowUp, ChevronRight, Clock3, MessageCircle, Trophy, Users } from "lucide-react"
import { badges, contests, difficultyClass, leaderboard, statusClass, threads, type ContestStatus } from "@/lib/contests"

const shell = "rounded-2xl border border-white/10 bg-white/[0.035]"

export function SectionTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { return <div className="flex items-end justify-between gap-4"><div>{eyebrow && <p className="text-xs uppercase tracking-[.25em] text-[#00D4FF]">{eyebrow}</p>}<h2 className="mt-2 text-2xl font-semibold tracking-tight text-white">{title}</h2></div>{action}</div> }

export function ContestCard({ contest, featured = false }: { contest: (typeof contests)[number]; featured?: boolean }) { return <article className={`${shell} ${featured ? "min-w-[330px]" : "min-w-0"} p-5`}><div className="flex items-start justify-between gap-3"><span className={`rounded-full border px-2.5 py-1 text-[11px] font-medium ${statusClass(contest.status)}`}>{contest.status}</span><span className={`text-xs font-medium ${difficultyClass(contest.difficulty)}`}>{contest.difficulty}</span></div><h3 className="mt-5 text-lg font-semibold text-white">{contest.title}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-white/55">{contest.description}</p><div className="mt-4 flex items-center gap-4 text-xs text-white/45"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{contest.countdown}</span><span className="flex items-center gap-1"><Users className="h-3.5 w-3.5" />{contest.participants}</span></div><Link href={`/contests/${contest.id}`} className="mt-5 flex items-center justify-center gap-2 rounded-xl border border-[#00D4FF]/40 bg-[#00D4FF]/10 px-3 py-2 text-sm font-medium text-[#00D4FF] transition hover:bg-[#00D4FF]/20">{contest.status === "Live" ? "Join Contest" : contest.status === "Upcoming" ? "Notify Me" : "View Results"}<ChevronRight className="h-4 w-4" /></Link></article> }

export function Podium() { return <div className="grid gap-3 md:grid-cols-3">{leaderboard.slice(0, 3).map((entry, index) => <div key={entry.rank} className={`${shell} p-5 ${index === 0 ? "md:-translate-y-3 border-[#F5B942]/35" : ""}`}><div className="flex items-center justify-between"><span className="text-2xl font-semibold text-[#F5B942]">#{entry.rank}</span><Trophy className="h-5 w-5 text-[#F5B942]" /></div><div className="mt-5 flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-full bg-gradient-to-br from-[#00D4FF] to-[#8B5CF6] text-sm font-bold text-[#07101a]">{entry.initials}</div><div><p className="font-medium text-white">{entry.username}</p><p className="text-xs text-white/45">{entry.xp.toLocaleString()} XP</p></div></div></div>)}</div> }

export function LeaderboardTable() { return <div className={`${shell} overflow-hidden`}><div className="grid grid-cols-[48px_1fr_90px_120px] gap-3 border-b border-white/10 px-5 py-3 text-[11px] uppercase tracking-wider text-white/35"><span>#</span><span>Explorer</span><span>XP</span><span>Streak</span></div>{leaderboard.map((entry) => <div key={entry.rank} className={`grid grid-cols-[48px_1fr_90px_120px] items-center gap-3 border-b border-white/5 px-5 py-4 text-sm last:border-0 ${entry.username === "Maya Chen" ? "bg-[#00D4FF]/10" : ""}`}><span className="font-semibold text-white/50">{entry.rank}</span><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full bg-white/10 text-[10px] font-semibold text-white">{entry.initials}</div><div><p className="font-medium text-white">{entry.username}</p><div className="flex gap-1 text-[10px] text-white/35">{entry.badges.slice(0, 2).join(" · ")}</div></div></div><span className="text-white/70">{entry.xp.toLocaleString()}</span><span className="text-[#FFB800]">{entry.streak} days</span></div>)}</div> }

export function DiscussionList() { const [sort, setSort] = useState("Top"); const [votes, setVotes] = useState<Record<string, boolean>>({}); return <div className="space-y-3"><div className="flex gap-2">{["Top", "New", "Most Replies"].map((item) => <button key={item} onClick={() => setSort(item)} className={`rounded-lg border px-3 py-1.5 text-xs ${sort === item ? "border-[#00D4FF]/40 bg-[#00D4FF]/10 text-[#00D4FF]" : "border-white/10 text-white/45"}`}>{item}</button>)}<button className="ml-auto rounded-lg bg-[#00D4FF] px-3 py-1.5 text-xs font-semibold text-[#07101a]">New Thread</button></div>{threads.map((thread) => <div key={thread.id} className={`${shell} flex gap-4 p-4`}><button onClick={() => setVotes((v) => ({ ...v, [thread.id]: !v[thread.id] }))} className={`flex flex-col items-center gap-1 text-xs ${votes[thread.id] ? "text-[#00D4FF]" : "text-white/40"}`}><ArrowUp className="h-4 w-4" />{thread.upvotes + (votes[thread.id] ? 1 : 0)}</button><div className="min-w-0 flex-1"><h3 className="font-medium text-white">{thread.title}</h3><p className="mt-1 text-xs text-white/45">{thread.author} · {thread.timestamp}</p><div className="mt-3 flex flex-wrap gap-2">{thread.tags.map((tag) => <span key={tag} className="rounded-md bg-white/5 px-2 py-1 text-[10px] text-white/45">{tag}</span>)}</div></div><span className="flex items-center gap-1 self-start text-xs text-white/40"><MessageCircle className="h-3.5 w-3.5" />{thread.replies}</span></div>)}</div> }

export function BadgeGrid() { return <div className="grid gap-3 sm:grid-cols-2">{badges.map(([name, description], index) => <div key={name} className={`${shell} flex items-center gap-3 p-4 ${index > 3 ? "opacity-45 grayscale" : ""}`}><div className="flex size-10 items-center justify-center rounded-xl border border-[#F5B942]/30 bg-[#F5B942]/10 text-lg text-[#F5B942]">✦</div><div><p className="text-sm font-medium text-white">{name}</p><p className="text-xs text-white/45">{description}</p></div></div>)}</div> }

export function FilterBar({ status, setStatus }: { status: ContestStatus | "All"; setStatus: (status: ContestStatus | "All") => void }) { return <div className="flex flex-wrap gap-2">{(["All", "Live", "Upcoming", "Ended"] as const).map((item) => <button key={item} onClick={() => setStatus(item)} className={`rounded-lg border px-3 py-2 text-xs ${status === item ? "border-[#00D4FF]/40 bg-[#00D4FF]/10 text-[#00D4FF]" : "border-white/10 text-white/50 hover:text-white"}`}>{item}</button>)}</div> }
    
